os: linux
language:
- minimal
services:
- docker

env:
- OS_FAMILY=centos OS_VERSION=7
- OS_FAMILY=centos OS_VERSION=8
- OS_FAMILY=debian OS_VERSION=10
- OS_FAMILY=fedora OS_VERSION=30
- OS_FAMILY=fedora OS_VERSION=31
- OS_FAMILY=ubuntu OS_VERSION=18.04
- OS_FAMILY=ubuntu OS_VERSION=19.04

script:
- pushd docker/${OS_FAMILY}-${OS_VERSION}
- tar -czh . | docker build -t ${DOCKER_USERNAME}/linuxbrew-${OS_FAMILY}:%{OS_VERSION} -
- popd
- docker build --build-arg OS_FAMILY=${OS_FAMILY} --build-arg OS_VERSION=${OS_VERSION} tests

after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push fastide/linuxbrew-${OS_FAMILY}:${OS_VERSION}